### PR TITLE
feat: implement driver click method

### PR DESCRIPTION
**Pull request by w0rse**
I was missing this method to test right clicks

### CODE REVIEW

**Comment by w0rse** [comment]
Not sure what to do about the CI build errors

**Comment by jkrems** [comment]
The problem is that the build tries to verify that none of the files changed and I'm guessing that the new version of coffee-script changes how things are compiled (re-created locally via `rm -rf node_modules && npm i && npm t`).

**Comment by jkrems** [comment]
Landed via https://github.com/groupon/webdriver-http-sync/pull/45. Thanks!

**Comment by w0rse** [comment]
Thank you for a fast merge!

**Pull request merged**
