### PR TITLE
Bundle http-sync

### PR DESCRIPTION
**Pull request by jkrems**
This decouples us from `http-sync` releases when the next version of node comes around.

For .travis.yml changes see: https://github.com/travis-ci/travis-ci/issues/4771

### CODE REVIEW

**Comment by khoomeister** [comment]
I guess there's a good reason for not keeping http-sync?

Also, do we need to include its tests as well?

**Comment by jkrems** [comment]
@khoomeister Since we are not exposing it, I think our current test coverage should be enough. I'd rather delete features from it we don't need than adding the test suite. The reason for this change is that each time we needed something like the nan upgrade, the blocking factor was release delays in http-sync. Which means that each time testium wasn't compatible with the latest node version, this was the critical path was the culprit.

**Comment by khoomeister** [comment]
Have we tried asking for commit & publish privileges to the repo?  Just make a case (we depend on it heavily) and see whether he's willing to trust you?

**Comment by khoomeister** [comment]
:shipit:

**Comment by EndangeredMassa** [comment]
I agree with @khoomeister. Can we try to get contributor access to http-sync instead?

**Comment by jkrems** [comment]
I'm currently cleaning up the code. I'm deleting what feels like 80% of it. I'd much rather maintain the subset we care about than all of `http-sync`.

**Comment by EndangeredMassa** [comment]
If it's really that small, then yeah, let's see what that looks like.

**Comment by jkrems** [comment]
See here: https://github.com/groupon/webdriver-http-sync/pull/31

**Comment by EndangeredMassa** [comment]
published in [1.2.0](https://github.com/groupon/webdriver-http-sync/releases/tag/v1.2.0)

**Pull request merged**
